{% set name = "pygplates" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://earthbyte.org/webdav/ftp/earthbyte/pygplates/pygplates_1.0.0rc1.post2_src.tar.bz2
  sha256: 0dd82ab3ad19f45dcb80d147389707dc525edd5e633571618044fdf9e961b8b1

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
  host:
    - python
    - pip
    - scikit-build-core <0.11  # avoid version 0.11 for now (causing problems with license.file)
    - numpy
    - cgal-cpp
    - gmp
    - mpfr
    - glew
    - libopengl-devel  # [linux]
    - libgl-devel      # [linux]
    - libglx-devel     # [linux]
    - libglu           # [linux]
    - xorg-libxfixes   # [linux]
    - qt-main
    - libboost-devel
    - libboost-python-devel
    - libgdal
    - proj
    - qwt
    - zlib
  run:
    - python
    - glew
    - libglu     # [linux]
    - qt-main
    - libgdal
    - proj
    - qwt
    - zlib

test:
  source_files:
    - pygplates/test
  imports:
    - pygplates
  commands:
    - python pygplates/test/test.py

about:
  home: https://www.gplates.org/
  summary: 'Python library for fine-grained access to GPlates functionality'
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://www.gplates.org/docs/pygplates/index.html
  dev_url: https://github.com/GPlates/GPlates

extra:
  recipe-maintainers:
    - jcannon-gplates
